### ISSUE TITLE
Catching exceptions inside the read_loop thread

### ISSUE THREAD

**Issue by comboy** [zcourts/websocket-td#5]
I've been encountering problems with losing websocket connection without on_close and on_error firing. It could be me, but it seems that in here

      @read_thread = Thread.new do
          read_loop
      end

when some exception is raised inside the read_loop we'll never know about it. I've been using https://github.com/comboy/catcher to just print exception to stderr I'm biased since it's my gem, but even without adding dependency it could simply be printed out to know that something went wrong (let's say some bug). 

May also be a good idea to catch IOError in there I guess, firing on_error/on_close. I can create a simple PR, just preferred to ask first, what do you think?

**Comment by zcourts** [comment]
Happy to accept a PR if you can.

**Comment by comboy** [comment]
Sorry for such a slow reply. Let me know if anything can be improved in the PR.

**Comment by zcourts** [comment]
Thanks for the PR. I took forever to get to this (apologies). 0.0.6 release out
